export const GET_REMINDERS_LIST = 'GET_REMINDERS_LIST'
export const ADD_REMINDER_TO_LIST = 'ADD_REMINDER_TO_LIST'
export const UPDATE_REMINDER_IN_LIST = 'UPDATE_REMINDER_IN_LIST'
export const REMOVE_REMINDER_FROM_LIST = 'REMOVE_REMINDER_FROM_LIST'
